name: Actualizar Cambio
on:
  schedule:
    - cron: '0 */4 * * *' # Se ejecuta cada 4 horas
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Instalar librerías
        run: pip install requests beautifulsoup4
      - name: Ejecutar scraper
        run: python bot.py
      - name: Guardar cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cambio.json
          git commit -m "Actualización automática" || exit 0
          git push
